### ISSUE TITLE
Unable to post to SNS when attempted from Amazon EC2

### ISSUE THREAD

**Issue by sahilsareen** [ixixi/fluent-plugin-sns#9]
Installed plugin using
==================
sudo td-agent-gem install fluent-plugin-sns

td-agent --version
===============
td-agent 0.12.20

Console output
=============
sudo /etc/init.d/td-agent status
td-agent is running

curl -X POST -d 'json={"json":"message"}' http://127.0.0.1:8827/test  <======= Failed                                                         
500 Internal Server Error
undefined method `publish' for nil:NilClass

curl -X POST -d 'json={"json":"message"}' http://127.0.0.1:8827/debug.test <==== Successful

td-agent.conf
=============
```
## match tag=debug.** and dump to console                                                                                                                                            
<match debug.**>
  type stdout
</match>

<match test>
  type sns
  sns_topic_name XXXX
  aws_key_id XXX
  aws_sec_key XXX
</match>

# HTTP input                                                                                                                                                                         
# POST http://localhost:8888/<tag>?json=<json>                                                                                                                                       
# POST http://localhost:8888/td.myapp.login?json={"user"%3A"me"}                                                                                                                     
# @see http://docs.fluentd.org/articles/in_http                                                                                                                                      
<source>
  type http
  port 8827
</source>
```
td-agent.log
=============
<pre>
2016-05-02 09:37:24 +0000 [info]: listening fluent socket on 0.0.0.0:24224
2016-05-02 09:37:24 +0000 [info]: listening dRuby uri="druby://127.0.0.1:24230" object="Engine"
2016-05-02 09:37:39 +0000 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `publish' for nil:NilClass" tag="test"
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sns-2.1.7/lib/fluent/plugin/out_sns.rb:71:in `block in emit'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/event.rb:54:in `call'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/event.rb:54:in `each'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-sns-2.1.7/lib/fluent/plugin/out_sns.rb:67:in `emit'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/event_router.rb:88:in `emit_stream'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/event_router.rb:79:in `emit'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/in_http.rb:186:in `on_request'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/in_http.rb:353:in `call'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/in_http.rb:353:in `on_message_complete'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/in_http.rb:255:in `<<'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/in_http.rb:255:in `on_read'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/io.rb:123:in `on_readable'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/io.rb:186:in `on_readable'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run_once'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run'
  2016-05-02 09:37:39 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.20/lib/fluent/plugin/in_http.rb:122:in `run'  <==== Failed
2016-05-02 09:37:50 +0000 debug.test: {"json":"message"}  <==== Successful 
</pre>

I was able to list the topics on SNS on ec2 as well so no issues with credentials

aws configure
=============
<pre>
AWS Access Key ID [****************XXXX]: 
AWS Secret Access Key [****************XXXX]: 
Default region name [us-east-1]: 
Default output format [json]: 
</pre>
aws sns list-topics
==============
<pre>
{
    "Topics": [
        {
            "TopicArn": "arn:aws:sns:us-east-1:XXX"
        }, 
        {
            "TopicArn": "arn:aws:sns:us-east-1:XXX"
        }
    ]
}
</pre>

**Comment by sahilsareen** [comment]
I missed adding the sns_endpoint in the config.
Resolving **NOTABUG**.
